FROM node:22-alpine
WORKDIR /app

# Install 'serve' globally so npx doesn't prompt for installation
RUN npm install -g serve

# Copy only the compiled files generated by GitHub Actions
COPY dist ./dist

EXPOSE 3000

# Run the global serve command directly
CMD ["serve", "-s", "dist", "-l", "3000"]