import React, { useState, useEffect, useRef } from "react";
import { Home, Trash, Eye, Download } from "lucide-react";
import { NavLink, useLocation } from "react-router-dom";
import { toast } from "react-toastify";
import api from "../../../api/axiosInstance";

// --- APIs ---
import { getClientInvoicesApi, deleteClientInvoiceApi, type ClientInvoiceData } from "../../../api/financeApi/clientInvoiceApi";
import { getClientsApi } from "../../../api/clientApi/clientApi";

// --- Components ---
import Select from "../../../components/ui/Select";
import Input from "../../../components/ui/Input";
import DatePicker from "../../../components/ui/DatePicker";
import DataTable from "../../../components/ui/DataTable";
import FilterCard from "../../../components/ui/FilterCard";
import AdvancedFilter, { type FilterColumn } from "../../../components/ui/AdvancedFilter";
import { DeleteModal } from "../../../components/modals/DeleteModal";
import ContextMenu, { type ContextMenuItem } from "../../../components/ui/ContextMenu";
import { usePagePermissions } from "../../../hooks/usePagePermissions";
import { actionHelper } from "../../../helper/action";

// FIXED: Import the timezone formatter
import { formatDateTime } from "../../../helper/dateFormatter";

interface Option { label: string; value: string; }
interface ColumnConfig extends FilterColumn { render?: (data: any) => React.ReactNode; options?: Option[]; filterKey?: string; }

const DEFAULT_SEARCH_COLUMNS = ["invoiceNumber", "clientName"];
const DEFAULT_TABLE_COLUMNS = [
  "invoiceNumber",
  "clientName",
  "billingPeriodStart",
  "billingPeriodEnd",
  "invoiceDate",
  "totalSegments",
  "totalAmount",
  "accountManagerName"
];

const formatDateToString = (date: Date | null) => {
  if (!date) return "";
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
};

const parseStringToDate = (dateStr: string | undefined) => {
  if (!dateStr) return null;
  const [year, month, day] = dateStr.split("-").map(Number);
  return new Date(year, month - 1, day);
};

const ClientInvoice: React.FC = () => {
  const { canDelete } = usePagePermissions();
  const [invoices, setInvoices] = useState<ClientInvoiceData[]>([]);
  const [totalItems, setTotalItems] = useState(0);
  const [isLoading, setIsLoading] = useState(true);

  const [clients, setClients] = useState<Option[]>([]);
  const [deleteId, setDeleteId] = useState<number | null>(null);

  const [contextMenuPos, setContextMenuPos] = useState<{ x: number; y: number } | null>(null);
  const [selectedRow, setSelectedRow] = useState<ClientInvoiceData | null>(null);

  const [searchColumns, setSearchColumns] = useState<string[]>(DEFAULT_SEARCH_COLUMNS);
  const [filterValues, setFilterValues] = useState<Record<string, string>>({});

  const [tableColumns, setTableColumns] = useState<string[]>(() => {
    const saved = localStorage.getItem("clientInvoice_table_columns_v3");
    try {
      return saved ? JSON.parse(saved) : DEFAULT_TABLE_COLUMNS;
    } catch (e) {
      return DEFAULT_TABLE_COLUMNS;
    }
  });

  useEffect(() => { localStorage.setItem("clientInvoice_table_columns_v3", JSON.stringify(tableColumns)); }, [tableColumns]);

  const [rowsPerPage, setRowsPerPage] = useState(10);
  const [currentPage, setCurrentPage] = useState(1);
  const location = useLocation();
  const routeName = location.pathname.split("/").pop() || "clientInvoice";
  const abortControllerRef = useRef<AbortController | null>(null);

  const hasLoggedOpening = useRef(false);

  useEffect(() => {
    if (!hasLoggedOpening.current) {
      setTimeout(() => { actionHelper("Client Invoice", `Opened Module`, false); }, 100);
      hasLoggedOpening.current = true;
    }
  }, []);

  useEffect(() => {
    getClientsApi("client", 1, 1000).then((res: any) => {
      const list = res.results || (Array.isArray(res) ? res : []);
      setClients(list.map((c: any) => ({ label: c.name, value: String(c.id) })));
    }).catch(() => console.error("Failed to load clients"));
  }, []);

  const allColumns: ColumnConfig[] = [
    { key: "invoiceNumber", label: "Invoice No.", type: "text" },
    { key: "clientName", label: "Client", type: "text", options: clients, filterKey: "client" },
    { key: "billingPeriodStart", label: "Period Start", type: "date" },
    { key: "billingPeriodEnd", label: "Period End", type: "date" },
    { key: "invoiceDate", label: "Invoice Date", type: "date" },
    { key: "totalSegments", label: "Total Segments", type: "number" },
    { key: "totalAmount", label: "Total Amount", type: "number" },
    { key: "accountManagerName", label: "Generated By", type: "text" },
    {
      key: "createdAt",
      label: "Created At",
      type: "date",
      // FIXED: Use the cached timezone helper instead of local browser time
      render: (data: any) => {
        if (!data.createdAt) return "-";
        return formatDateTime(data.createdAt);
      }
    }
  ];

  const visibleSearchFields = allColumns.filter((col) => searchColumns.includes(col.key));
  const visibleTableFields = allColumns.filter((col) => tableColumns.includes(col.key));

  const fetchInvoices = async (filters: Record<string, string> | null = null) => {
    if (abortControllerRef.current) abortControllerRef.current.abort();
    const newController = new AbortController(); abortControllerRef.current = newController;
    setIsLoading(true);
    try {
      const activeFilters = filters || filterValues;
      const currentSearchParams: Record<string, string> = {};
      searchColumns.forEach((key) => {
        const value = activeFilters[key];
        if (value) {
          const columnDef = allColumns.find((c) => c.key === key);
          if (columnDef?.options) {
            const selectedOption = columnDef.options.find((opt: Option) => opt.value === value);
            currentSearchParams[columnDef.filterKey || key] = selectedOption ? selectedOption.value : value;
          } else { currentSearchParams[columnDef?.filterKey || key] = value; }
        }
      });
      const response: any = await getClientInvoicesApi(routeName, currentPage, rowsPerPage, currentSearchParams);
      if (newController.signal.aborted) return;
      if (response && response.results) { setInvoices(response.results); setTotalItems(response.count); }
      else { setInvoices([]); setTotalItems(0); }
    } catch (error) { console.error("Pending backend"); }
    finally { if (abortControllerRef.current === newController) setIsLoading(false); }
  };

  useEffect(() => { fetchInvoices(); return () => { if (abortControllerRef.current) abortControllerRef.current.abort(); }; }, [currentPage, rowsPerPage, searchColumns]);

  const handleDelete = async () => {
    if (deleteId && canDelete) {
      try { await deleteClientInvoiceApi(deleteId, routeName); toast.success("Invoice deleted."); fetchInvoices(); }
      catch (error) { toast.error("Failed to delete."); } setDeleteId(null);
    }
  };
  const VITE_IMAGE_URL = import.meta.env.VITE_IMAGE_URL;
  const handleViewPdf = (path?: string) => {
    if (!path) { toast.error("PDF not available yet."); return; }

    // 1. If path already includes 'http', it's likely a downloadUrl (don't touch it)
    // 2. If it's your new relative path (media/...), prepend VITE_IMAGE_URL
    const fullUrl = path.startsWith("http")
      ? path
      : `${VITE_IMAGE_URL}/${path}`;

    // Clean up any accidental double slashes created by the concatenation
    const cleanUrl = fullUrl.replace(/(?<!:)\/\//g, "/");

    window.open(cleanUrl, "_blank");
  };

  const handleDownloadPdf = async (url?: string) => {
    if (!url) { toast.error("Download link not available."); return; }
    const cleanUrl = url.replace(/^None\/?/, "/").replace(/(?<!:)\/\//g, "/");

    try {
      const response = await api.get(cleanUrl, { responseType: "blob" });
      const blobUrl = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement("a");
      link.href = blobUrl;
      link.setAttribute("download", cleanUrl.split("/").pop() || "invoice.pdf");
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(blobUrl);
      toast.success("PDF downloaded successfully!");
    } catch (error) {
      toast.error("Failed to download PDF.");
    }
  };

  const handleDownloadEdr = async (id?: number) => {
    if (!id) { toast.error("Invoice ID not available."); return; }

    try {
      const response = await api.get(`/finance/TDR-invoice/download/${id}/`, { responseType: "blob" });
      const blobUrl = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement("a");
      link.href = blobUrl;
      link.setAttribute("download", `EDR-${id}.csv`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(blobUrl);
      toast.success("EDR downloaded successfully!");
    } catch (error) {
      toast.error("Failed to download EDR.");
    }
  };

  const menuItems: ContextMenuItem[] = selectedRow ? [
    { label: "View Invoice", icon: <Eye size={16} />, onClick: () => handleViewPdf(selectedRow.invoicePdf) },
    { label: "Download PDF", icon: <Download size={16} />, onClick: () => handleDownloadPdf(selectedRow.downloadUrl || selectedRow.invoicePdf) },
    { label: "Download EDR", icon: <Download size={16} />, onClick: () => handleDownloadEdr(selectedRow.id) },
    ...(canDelete ? [{ label: "Delete Invoice", icon: <Trash size={16} />, variant: "danger" as const, onClick: () => setDeleteId(selectedRow.id!) }] : []),
  ] : [];

  return (
    <div className="container mx-auto" onClick={() => setContextMenuPos(null)}>
      <div className="mb-6 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4">
          <h1 className="text-2xl font-semibold text-text-primary dark:text-white mr-2">Client Invoices</h1>
          <div className="relative z-20"><AdvancedFilter columns={allColumns} selectedColumns={searchColumns} onFilter={setSearchColumns} onClear={() => setSearchColumns(DEFAULT_SEARCH_COLUMNS)} isLoading={isLoading} buttonLabel="Search Fields" /></div>
          <div className="relative z-20"><AdvancedFilter columns={allColumns} selectedColumns={tableColumns} onFilter={setTableColumns} onClear={() => setTableColumns(DEFAULT_TABLE_COLUMNS)} buttonLabel="Columns" /></div>
        </div>

        <div className="flex items-center space-x-2 text-sm text-text-secondary">
          <Home size={16} className="text-gray-400" />
          <NavLink to="/dashboard" className="text-gray-400 hover:text-primary">Home</NavLink>
          <span>/</span><span className="text-text-primary dark:text-white">Finance</span>
          <span>/</span><span className="text-text-primary dark:text-white">Client Invoice</span>
        </div>
      </div>

      <FilterCard onSearch={() => { setCurrentPage(1); fetchInvoices(); }} onClear={() => { setFilterValues({}); setCurrentPage(1); fetchInvoices({}); }}>
        {visibleSearchFields.map((col) => {
          if (col.options) {
            return (
              <Select
                key={col.key}
                label={`Search ${col.label}`}
                value={filterValues[col.key] || ""}
                onChange={(val) => setFilterValues(p => ({ ...p, [col.key]: val }))}
                options={col.options}
                placeholder={`Select ${col.label}`}
              />
            );
          }
          if (col.type === "date") {
            return (
              <DatePicker
                key={col.key}
                label={`Search ${col.label}`}
                selected={parseStringToDate(filterValues[col.key])}
                onChange={(dateVal) => setFilterValues(p => ({ ...p, [col.key]: formatDateToString(dateVal) }))}
                placeholder={`Select ${col.label}`}
              />
            );
          }
          return (
            <Input
              key={col.key}
              label={`Search ${col.label}`}
              value={filterValues[col.key] || ""}
              onChange={(e) => setFilterValues(p => ({ ...p, [col.key]: e.target.value }))}
              placeholder={`Search ${col.label}`}
            />
          );
        })}
      </FilterCard>

      <DataTable
        serverSide={true} data={invoices} totalItems={totalItems} currentPage={currentPage} rowsPerPage={rowsPerPage}
        onPageChange={setCurrentPage} onRowsPerPageChange={setRowsPerPage} headers={["S.N.", ...visibleTableFields.map(c => c.label)]} isLoading={isLoading}
        renderRow={(invoice, index) => (
          <tr key={invoice.id || index} onContextMenu={(e) => { e.preventDefault(); setContextMenuPos({ x: e.clientX, y: e.clientY }); setSelectedRow(invoice); }} className="hover:bg-gray-50 dark:hover:bg-gray-700 border-b border-gray-200 dark:border-gray-700 cursor-context-menu">
            <td className="px-4 py-4 text-sm text-text-primary dark:text-white">{(currentPage - 1) * rowsPerPage + index + 1}</td>
            {visibleTableFields.map((col) => {
              let cellContent: React.ReactNode = "-";
              const rawValue = (invoice as any)[col.key];

              if (col.render) {
                cellContent = col.render(invoice);
              } else if (col.key === "totalAmount") {
                cellContent = rawValue != null && !isNaN(Number(rawValue)) ? `$${Number(rawValue).toFixed(2)}` : "-";
              } else {
                cellContent = rawValue || "-";
              }

              return (
                <td key={col.key} className={`px-4 py-4 text-sm text-text-secondary dark:text-gray-300 whitespace-nowrap ${col.key === "invoiceNumber" ? "font-medium text-primary" : ""}`}>
                  {cellContent}
                </td>
              );
            })}
          </tr>
        )}
      />

      <ContextMenu position={contextMenuPos} items={menuItems} onClose={() => setContextMenuPos(null)} />
      <DeleteModal isOpen={!!deleteId} onClose={() => setDeleteId(null)} onConfirm={handleDelete} title="Delete Invoice" message="Are you sure you want to delete this invoice?" />
    </div>
  );
};

export default ClientInvoice;